### ISSUE TITLE
NoSuchMethodError in Latest Forge Versions for ControlledAttackGoal

### ISSUE THREAD

**Issue by Alphapowers777** [WolfShotz/Wyrmroost#119]
19:38:51] [Server thread/INFO] [minecraft/DedicatedServer]: Alphapowers joined the game >....
[19:38:51] [Netty Epoll Server IO #2/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.ModIdArgument@77703a7c (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client! >....
[19:38:51] [Netty Epoll Server IO #2/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.EnumArgument@798a59d3 (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client! >....
rate limit exceeded
[19:38:56] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID ce060f77-dd35-4f95-a1e4-86e91ee1c40d >....
[19:38:56] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception net.minecraft.crash.ReportedException: Ticking entity at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:283) ~[?:?] {re:classloading,pl:accesstransformer:B} at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:783) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:638) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265] {} Caused by: java.lang.NoSuchMethodError: WolfShotz.Wyrmroost.entities.dragon.AbstractDragonEntity.func_184215_y(Lnet/minecraft/entity/Entity;)Z at WolfShotz.Wyrmroost.entities.dragon.helpers.ai.goals.ControlledAttackGoal.func_190102_a(ControlledAttackGoal.java:42) ~[?:1.2.4] {re:classloading} at net.minecraft.entity.ai.goal.MeleeAttackGoal.func_75246_d(MeleeAttackGoal.java:130) ~[?:?] {re:classloading} at WolfShotz.Wyrmroost.entities.dragon.helpers.ai.goals.ControlledAttackGoal.func_75246_d(ControlledAttackGoal.java:36) ~[?:1.2.4] {re:classloading} at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:classloading} at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_265] {} at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_265] {} at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_265] {} at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_265] {} at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_265] {} at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_265] {} at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_265] {} at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_265] {} at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_265] {} at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_265] {} at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:88) ~[?:?] {re:classloading,pl:accesstransformer:B} at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:682) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?] {re:classloading} at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:51) ~[?:?] {re:classloading,pl:runtimedistcleaner:A} at WolfShotz.Wyrmroost.entities.dragon.AbstractDragonEntity.func_70636_d(AbstractDragonEntity.java:237) ~[?:1.2.4] {re:classloading} at WolfShotz.Wyrmroost.entities.dragon.OWDrakeEntity.func_70636_d(OWDrakeEntity.java:135) ~[?:1.2.4] {re:classloading} at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} at net.minecraft.entity.MobE
ntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} at WolfShotz.Wyrmroost.entities.dragon.AbstractDragonEntity.func_70071_h_(AbstractDragonEntity.java:225) ~[?:1.2.4] {re:classloading} at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:606) ~[?:?] {re:classloading,pl:runtimedistcleaner:A} at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:399) ~[?:?] {re:classloading,pl:runtimedistcleaner:A} at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:847) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} ... 5 more >....
Command
Here you can send commands directly to the server.

**Comment by Grillby256** [comment]
Ive been having the same problem with the drake when its about to attack it freezes up and then boom a sever crash I would love it if this was fixed soon as yo be able to play with this mod its amazing and I hope all works out.

**Comment by WolfShotz** [comment]
It appears that in newer forge versions a method I use in the attack goal no longer exists... for some reason. There isn't supposed to be breaking changes so that's cute. Will work something out soon

**Comment by CorgiTaco** [comment]
Is this crash related? https://hatebin.com/ysvactfhky

**Comment by WolfShotz** [comment]
Looks to be, yes
