### ISSUE TITLE
Game crashes when a drake kicks me off.

### ISSUE THREAD

**Issue by RhylieMines** [WolfShotz/Wyrmroost#122]
Whenever I try to mount a drake and it kicks me off, I get this error:

Time: 10/16/20 4:37 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.ai.controller.LookController.func_75651_a(SourceFile:31) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.goal.MeleeAttackGoal.func_75246_d(MeleeAttackGoal.java:98) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.ai.goal.GoalSelector$$Lambda$18332/508150986.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_51] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:80) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:595) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2262) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,xf:fml:astralsorcery:set_player_field,xf:fml:astralsorcery:water_movement_slowdown_prevention,xf:fml:astralsorcery:elytra_living_update_tick}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:462) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:159) ~[?:?] {re:classloading}
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(SourceFile:44) ~[?:?] {re:classloading}
	at WolfShotz.Wyrmroost.entities.dragon.AbstractDragonEntity.func_70636_d(AbstractDragonEntity.java:239) ~[?:1.2.4] {re:classloading}
	at WolfShotz.Wyrmroost.entities.dragon.OWDrakeEntity.func_70636_d(OWDrakeEntity.java:144) ~[?:1.2.4] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothshieldblock,xf:fml:apotheosis:apothpotiondmg,xf:fml:astralsorcery:set_player_field,xf:fml:astralsorcery:water_movement_slowdown_prevention,xf:fml:astralsorcery:elytra_living_update_tick}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at WolfShotz.Wyrmroost.entities.dragon.AbstractDragonEntity.func_70071_h_(AbstractDragonEntity.java:227) ~[?:1.2.4] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600) ~[?:?] {re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook}
	at net.minecraft.world.server.ServerWorld$$Lambda$18308/782972151.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:536) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401) ~[?:?] {re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.ai.controller.LookController.func_75651_a(SourceFile:31)
	at net.minecraft.entity.ai.goal.MeleeAttackGoal.func_75246_d(MeleeAttackGoal.java:98)
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55)
	at net.minecraft.entity.ai.goal.GoalSelector$$Lambda$18332/508150986.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:80)
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:595)
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2262)
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:462)
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:159)
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(SourceFile:44)
	at WolfShotz.Wyrmroost.entities.dragon.AbstractDragonEntity.func_70636_d(AbstractDragonEntity.java:239)
	at WolfShotz.Wyrmroost.entities.dragon.OWDrakeEntity.func_70636_d(OWDrakeEntity.java:144)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274)
	at WolfShotz.Wyrmroost.entities.dragon.AbstractDragonEntity.func_70071_h_(AbstractDragonEntity.java:227)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600)
	at net.minecraft.world.server.ServerWorld$$Lambda$18308/782972151.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: wyrmroost:overworld_drake (WolfShotz.Wyrmroost.entities.dragon.OWDrakeEntity)
	Entity ID: 21
	Entity Name: Overworld Drake
	Entity's Exact location: -298.70, 32.00, -23.98
	Entity's Block location: World: (-299,32,-24), Chunk: (at 5,2,8 in -19,-2; contains blocks -304,0,-32 to -289,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:536)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['_RhylieMines_'/29, l='Test', x=-295.02, y=32.00, z=-15.82]]
	Chunk stats: ServerChunkCache: 2101
	Level dimension: DimensionType{minecraft:overworld}
	Level name: Test
	Level seed: 1197413122865500942
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: {biome:"minecraft:plains",layers:[{block:"minecraft:bedrock",height:1b},{block:"minecraft:dirt",height:30b},{block:"minecraft:grass_block",height:1b}],structures:{village:{}}}
	Level spawn location: World: (-208,32,16), Chunk: (at 0,2,0 in -13,1; contains blocks -208,0,16 to -193,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 78581 game time, 5270 day time
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4619753240 bytes (4405 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.41.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.41.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.41.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.41.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.41.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.41
	FML Language Providers: 
		javafml@31.2
		minecraft@1
		kotlinfml@1.5.2
	Mod List: 
		QuarkOddities-1.15.2.jar Quark Oddities {quarkoddities@1.15.2 DONE}
		Craft_and_Hunt_V1.1.0_MC_1.15.2.jar Craft and Hunt {craftandhunt@0.9 DONE}
		astralsorcery-1.15.2-1.12.9.jar Astral Sorcery {astralsorcery@1.15.2-1.12.9 DONE}
		hatstands-1.0.1-1.15.2.jar Hat Stands {hatstands@1.0.1 DONE}
		damage_indicator-0.1.0.jar Ama's Damage Indicator {damage_indicator@0.0.9 DONE}
		Wyrmroost-1.15.2-1.2.4.jar Wyrmroost {wyrmroost@1.2.4 DONE}
		berry_good-2.0.0.jar Berry Good {berry_good@2.0 DONE}
		jei-1.15.2-6.0.3.15.jar Just Enough Items {jei@6.0.3.15 DONE}
		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 DONE}
		Bamboo-Blocks-1.15.2-1.4.1.jar Bamboo Blocks {bambooblocks@NONE DONE}
		Buzzier-Bees-1.15.2-1.5.2.jar Buzzier Bees {buzzierbees@1.5.2 DONE}
		goblintraders-1.2.0-1.15.2.jar Goblin Traders {goblintraders@1.2.0 DONE}
		flower-breeding-1.15.2-1.4.jar Lizzie's Flower Breeding {acmc@1.0 DONE}
		Upgrade-Aquatic-1.15.2-1.7.1.jar Upgrade Aquatic {upgrade_aquatic@1.7.1 DONE}
		strawgolem-1.15.2-1.9.jar Straw Golem {strawgolem@1.15.2-1.9 DONE}
		Bloomful-1.15.2-1.4.1.jar Bloomful {bloomful@NONE DONE}
		Guide-API-VP-1.15.2-2.2.1.jar Guide-API VP {guideapi-vp@2.2.1 DONE}
		extraboats-1.3.6-1.15.2.jar Extra Boats {extraboats@1.3.6 DONE}
		Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 DONE}
		MoreOresInONE-1.1_1.15.2.jar More Ores in ONE {moreoresinone@1.1 DONE}
		NeverNeededOrWanted-1.15.2-1.0.0.jar Never Needed Or Wanted {nnow@1.0.0 DONE}
		journeymap-1.15.2-5.7.0b3.jar Journeymap {journeymap@5.7.0b3 DONE}
		Placebo-1.15.2-3.1.0.jar Placebo {placebo@3.1.0 DONE}
		citadel-1.1.11.jar Citadel {citadel@1.1.11 DONE}
		TravelersBackpack-1.15.2-4.0.8.jar Traveler's Backpack {travelersbackpack@4.0.8 DONE}
		NaturesCompass-1.15.2-1.8.4.jar Nature's Compass {naturescompass@1.15.2-1.8.4 DONE}
		gemsnjewels-1.15.2-0.13.0.jar Gems & Jewels {gemsnjewels@0.13.1 DONE}
		betteranimalsplus-1.15.2-8.2.1.96.jar Better Animals Plus {betteranimalsplus@8.2.1.96 DONE}
		Reliquary-1.15.2-1.3.4.995.jar Reliquary {xreliquary@1.15.2-1.3.4.995 DONE}
		wizardstaff-1.15.2-1.0.0.jar Wizard Staff {wizard-staff@1.15.2-1.0.0 DONE}
		oceangems-1.0.0_1.15.2.jar Ocean Gems {ocean_gems@1.0.0 DONE}
		guardvillagers-1.15.2-1.0.8.jar Guard Villagers {guardvillagers@1.0.7 DONE}
		TinyMobFarm-1.15.2-1.0.8.jar Tiny Mob Farm {tinymobfarm@1.0.8 DONE}
		Apotheosis-1.15.2-3.3.7.jar Apotheosis {apotheosis@3.3.7 DONE}
		additional_lights-1.15.2-2.0.2.jar Additional Lights {additional_lights@2.0.2 DONE}
		iceandfire-2.1.0-1.15.2.jar Ice and Fire {iceandfire@2.0.3-1.15.2 DONE}
		Vulcan-Revenge-Mod-Plus+v1.15-1.15.2.jar Vulcan's Revenge Plus+ Mod {vrm@1.0 DONE}
		Shadowlands+1.15.2+version+2.0.jar Shadowlands {shadowlands@2.0.0 DONE}
		JustEnoughResources-1.15.2-0.10.1.77.jar Just Enough Resources {jeresources@0.10.1.77 DONE}
		Swamp-Expansion-1.15.2-1.7.3.jar Swamp Expansion {swampexpansion@NONE DONE}
		forge-1.15.2-31.2.41-universal.jar Forge {forge@31.2.41 DONE}
		Atum-1.15.2-2.1.6.jar Atum 2 {atum@1.15.2-2.1.6 DONE}
		respawnablepets-1.1.4.jar Respawnable Pets {respawnablepets@1.1.4 DONE}
		RottenCreatures-1.15.2-0.9.7.jar Rotten Creatures {rotten_creatures@0.9.7 DONE}
		forge-1.15.2-31.2.41-client.jar Minecraft {minecraft@1.15.2 DONE}
		The-Endergetic-Expansion-1.15.2-v1.3.2.jar The Endergetic Expansion {endergetic@1.3.2 DONE}
		BiomesOPlenty-1.15.2-10.0.0.366-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.366 DONE}
		LetSleepingDogsLie-1.15.2-1.1.1.jar Let Sleeping Dogs Lie {dogslie@1.1.1 DONE}
		BetterDefaultBiomes-1.15.2-Alpha+1.3.5.jar Better Default Biomes {betterdefaultbiomes@Alpha 1.3.5 DONE}
		fairylights-3.0.10-1.15.2.jar Fairy Lights {fairylights@3.0.10 DONE}
		Atmospheric-1.15.2-1.4.1.jar Atmospheric {atmospheric@1.4.1 DONE}
		Bountiful-1.15.2-3.1.2.jar Bountiful {bountiful@1.15.2-3.1.2 DONE}
		gaiadimension-1.15.2-1.2.2.jar The Gaia Dimension {gaiadimension@1.2.2 DONE}
		curios-FORGE-1.15.2-2.0.2.6.jar Curios API {curios@FORGE-1.15.2-2.0.2.6 DONE}
		Savage-and-Ravage-1.15.2-1.1.4.jar Savage & Ravage {savageandravage@1.1.4 DONE}
		Patchouli-1.15.2-1.2-35.jar Patchouli {patchouli@1.15.2-1.2-35 DONE}
		Mantle-1.15.2-1.5.15.jar Mantle {mantle@1.5.15 DONE}
		Inspirations-1.15.2-1.1.0.jar Inspirations {inspirations@1.15.2-1.1.0 DONE}
		flying_things-1.8.9-1.15.2.jar The Flying Things {flying_things@1.8.9 DONE}
		enchantedwolves-1.4.2.jar Enchanted Wolves {enchantedwolves@1.4.2 DONE}
		rats-5.3.2-1.15.2.jar Rats {rats@5.3.2 DONE}
		collective-1.15.2-1.39.jar Collective {collective@1.39 DONE}
		placeableitems-4.2.1.jar Placeable Items {placeableitems@4.2.1 DONE}
		autumnity-1.3.3-1.15.2.jar Autumnity {autumnity@1.3.3 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		WorldOfWonder-1.15.2-1.1.4.jar World of Wonder {worldofwonder@1.15.2-1.1.4 DONE}
		Sullys-Mod--v0.7--1.15.2--forge.jar Sully's Mod {sullys_mod@V0.8 DONE}
		themidnight-0.5.9.jar The Midnight {midnight@0.5.9 DONE}
		polyores-2.0.jar Poly's Ores {polyores@2.0 DONE}
		tombstone-4.5.6.jar Corail Tombstone {tombstone@4.5.6 DONE}
		Quark-r2.1-245.jar Quark {quark@r2.1-245 DONE}
		Enhanced-Mushrooms-1.15.2-v1.2.2.jar Enhanced Mushrooms {enhanced_mushrooms@$1.1.0 DONE}
		worldedit-forge-mc1.15.2-7.1.0.jar WorldEdit {worldedit@7.1.0;48cc31c DONE}
		TheAbyss+3.0.1+1.15.2.jar TheAbyss {theabyss@3.0.0b1 DONE}
		morevanillaarmor-1.15.2-1.2.jar MoreVanillaArmor {morevanillaarmor@1.15.2-1.2 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		Vampirism-1.15.2-1.6.1.jar Vampirism {vampirism@1.6.1 DONE, teamlapenlib@1.6.1 DONE}
		nametagtweaks_1.15-1.0.jar Name Tag Tweaks {nametagtweaks@1.0 DONE}
		connectedglass-1.0.6-mc1.15.jar Connected Glass {connectedglass@1.0.6 DONE}
		occultism-0.2.11.jar Occultism {occultism@0.2.11 DONE}
		observerlib-1.15.2-1.2.0.v60.jar ObserverLib {observerlib@1.15.2-1.2.0 DONE}
		productivebees-1.15.2-0.3.3.jar Productive Bees {productivebees@1.15.2-0.3.3 DONE}
		++Ores+1.15.2.jar ++Ores {more_ores@1.15.2 DONE}
		SakuraRosea-1.5.7-MC1.15.2.jar Sakura Rosea {sakurarosea@1.5.7 DONE}
		BoundTotems-1.15.2-1.4.0.jar Bound Totems {boundtotems@1.15.2-1.3.1 DONE}
		ilikewood-1.15.2-2.2.2.0.jar I Like Wood {ilikewood@1.15.2-2.2.2.0 DONE}
		enchantwithmob-1.15.2-1.0.0.jar Enchant With Mob {enchantwithmob@1.15.2-1.0.0 DONE}
		incubation-1.0.4-1.15.2.jar Incubation {incubation@1.0.4 DONE}
		disney-1.0.3-1.15.2.jar LDShadowLady's Disney Wish {disney@1.0.3-1.15.2 DONE}
		NetherEx-1.15.2-4.0.0.jar NetherEx {netherex@4.0.0 DONE}
		LibraryEx-1.15.2-3.0.0.jar LibraryEx {libraryex@3.0.0 DONE}
		SuperTools-1.1_1.15.2.jar Super Tools {supertools@1.1 DONE}
	Pulsar/inspirations loaded Pulses: 
		- InspirationsShared (Enabled/Forced)
		- InspirationsBuilding (Enabled/Not Forced)
		- InspirationsUtility (Enabled/Not Forced)
		- InspirationsTools (Enabled/Not Forced)
		- InspirationsTweaks (Enabled/Not Forced)

	Patchouli open book context: n/a
	Player Count: 1 / 8; [ServerPlayerEntity['_RhylieMines_'/29, l='Test', x=-295.02, y=32.00, z=-15.82]]
	Data Packs: netherex:netherex_nether_biome_pack (incompatible), netherex:default_nether_biome_pack (incompatible), netherex:bop_nether_biome_pack (incompatible), vanilla, mod:quarkoddities, mod:craftandhunt (incompatible), mod:astralsorcery (incompatible), mod:hatstands, mod:damage_indicator (incompatible), mod:wyrmroost (incompatible), mod:berry_good (incompatible), mod:jei (incompatible), mod:abnormals_core, mod:bambooblocks (incompatible), mod:buzzierbees, mod:goblintraders, mod:acmc (incompatible), mod:upgrade_aquatic (incompatible), mod:strawgolem, mod:bloomful (incompatible), mod:guideapi-vp (incompatible), mod:extraboats, mod:waystones (incompatible), mod:moreoresinone (incompatible), mod:nnow, mod:journeymap (incompatible), mod:placebo (incompatible), mod:citadel (incompatible), mod:travelersbackpack, mod:naturescompass (incompatible), mod:gemsnjewels, mod:betteranimalsplus (incompatible), mod:xreliquary (incompatible), mod:wizard-staff, mod:ocean_gems, mod:guardvillagers (incompatible), mod:tinymobfarm (incompatible), mod:apotheosis (incompatible), mod:additional_lights (incompatible), mod:iceandfire, mod:vrm, mod:shadowlands, mod:jeresources (incompatible), mod:swampexpansion (incompatible), mod:forge (incompatible), mod:atum (incompatible), mod:respawnablepets, mod:rotten_creatures, mod:endergetic (incompatible), mod:biomesoplenty, mod:dogslie (incompatible), mod:betterdefaultbiomes, mod:fairylights, mod:atmospheric, mod:bountiful (incompatible), mod:gaiadimension (incompatible), mod:curios (incompatible), mod:savageandravage, mod:patchouli (incompatible), mod:mantle (incompatible), mod:inspirations (incompatible), mod:flying_things, mod:enchantedwolves, mod:rats (incompatible), mod:collective (incompatible), mod:placeableitems (incompatible), mod:autumnity, mod:autoreglib (incompatible), mod:worldofwonder, mod:sullys_mod, mod:midnight, mod:polyores, mod:tombstone, mod:quark, mod:enhanced_mushrooms, mod:worldedit (incompatible), mod:theabyss, mod:morevanillaarmor, mod:cfm (incompatible), mod:vampirism (incompatible), mod:nametagtweaks (incompatible), mod:connectedglass, mod:occultism, mod:observerlib (incompatible), mod:productivebees, mod:more_ores, mod:sakurarosea, mod:boundtotems, mod:ilikewood, mod:enchantwithmob, mod:incubation, mod:disney, mod:netherex (incompatible), mod:libraryex (incompatible), mod:supertools (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by HockeyZman2000** [comment]
Same problem here. Funnily enough the name of your world is the exact same as mine haha.

**Comment by WolfShotz** [comment]
This is in 1.15, Im not supporting 1.15 anymore. sorry :/
