### ISSUE TITLE
follow ai crash

### ISSUE THREAD

**Issue by ApprenticeNecromancer** [WolfShotz/Wyrmroost#8]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 23.09.19 12:19
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.Entity.func_70068_e(Entity.java:1188) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.entity.ai.goal.FollowOwnerGoal.func_75253_b(SourceFile:65) ~[?:?] {}
	at WolfShotz.Wyrmroost.util.entityhelpers.ai.goals.DragonFollowOwnerGoal.func_75253_b(DragonFollowOwnerGoal.java:62) ~[?:1.0.0] {}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75253_b(SourceFile:27) ~[?:?] {}
	at net.minecraft.entity.ai.goal.GoalSelector.func_220881_e(SourceFile:55) ~[?:?] {}
	at net.minecraft.entity.ai.goal.GoalSelector$$Lambda$3758/962177859.test(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_51] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:55) ~[?:?] {}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:843) ~[?:?] {pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2186) ~[?:?] {}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:642) ~[?:?] {pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:140) ~[?:?] {}
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(SourceFile:44) ~[?:?] {}
	at WolfShotz.Wyrmroost.content.entities.dragon.AbstractDragonEntity.func_70636_d(AbstractDragonEntity.java:257) ~[?:1.0.0] {}
	at WolfShotz.Wyrmroost.content.entities.dragon.sliverglider.SilverGliderEntity.func_70636_d(SilverGliderEntity.java:131) ~[?:1.0.0] {}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2032) ~[?:?] {}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:397) ~[?:?] {pl:accesstransformer:B,xf:OptiFine:default}
	at WolfShotz.Wyrmroost.content.entities.dragon.AbstractDragonEntity.func_70071_h_(AbstractDragonEntity.java:265) ~[?:1.0.0] {}
	at WolfShotz.Wyrmroost.content.entities.dragon.sliverglider.SilverGliderEntity.func_70071_h_(SilverGliderEntity.java:136) ~[?:1.0.0] {}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587) ~[?:?] {}
	at net.minecraft.world.server.ServerWorld$$Lambda$3750/2037518411.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:684) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394) ~[?:?] {}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:161) ~[?:?] {xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.Entity.func_70068_e(Entity.java:1188)
	at net.minecraft.entity.ai.goal.FollowOwnerGoal.func_75253_b(SourceFile:65)
	at WolfShotz.Wyrmroost.util.entityhelpers.ai.goals.DragonFollowOwnerGoal.func_75253_b(DragonFollowOwnerGoal.java:62)
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75253_b(SourceFile:27)
	at net.minecraft.entity.ai.goal.GoalSelector.func_220881_e(SourceFile:55)
	at net.minecraft.entity.ai.goal.GoalSelector$$Lambda$3758/962177859.test(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:55)
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:843)
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2186)
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:642)
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:140)
	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(SourceFile:44)
	at WolfShotz.Wyrmroost.content.entities.dragon.AbstractDragonEntity.func_70636_d(AbstractDragonEntity.java:257)
	at WolfShotz.Wyrmroost.content.entities.dragon.sliverglider.SilverGliderEntity.func_70636_d(SilverGliderEntity.java:131)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2032)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:397)
	at WolfShotz.Wyrmroost.content.entities.dragon.AbstractDragonEntity.func_70071_h_(AbstractDragonEntity.java:265)
	at WolfShotz.Wyrmroost.content.entities.dragon.sliverglider.SilverGliderEntity.func_70071_h_(SilverGliderEntity.java:136)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587)
	at net.minecraft.world.server.ServerWorld$$Lambda$3750/2037518411.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: wyrmroost:silver_glider (WolfShotz.Wyrmroost.content.entities.dragon.sliverglider.SilverGliderEntity)
	Entity ID: 955
	Entity Name: Silver Glider
	Entity's Exact location: 78.26, 75.76, 849.76
	Entity's Block location: World: (78,75,849), Chunk: (at 14,4,1 in 4,53; contains blocks 64,0,848 to 79,255,863), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Entity's Momentum: 0.05, -0.30, -0.05
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:684)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Nigrumrana'/33, l='1.14.4 test', x=68.88, y=73.00, z=858.58]]
	Chunk stats: ServerChunkCache: 3925
	Level dimension: DimensionType{minecraft:overworld}
	Level name: 1.14.4 test
	Level seed: -2898025821902362310
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (-64,65,192), Chunk: (at 0,4,0 in -4,12; contains blocks -64,0,192 to -49,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 153827 game time, 10322 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:161)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6068430936 bytes (5787 MB) / 8556380160 bytes (8160 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.0.92.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.92.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.0.92.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.92.jar runtimedistcleaner PLUGINSERVICE 
		/OptiFine_1.14.4_HD_U_F4_pre4_MOD.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.0.92.jar fml TRANSFORMATIONSERVICE 
	FML: 28.0
	Forge: net.minecraftforge:28.0.92
	FML Language Providers: 
		javafml@28.0
		minecraft@1
	Mod List: 
		citadel-1.0.0.jar Citadel {citadel@1.0.0 DONE}
		Wyrmroost-1.14.4-1.0.0.jar Wyrmroost {wyrmroost@1.0.0 DONE}
		forge-1.14.4-28.0.92-universal.jar Forge {forge@28.0.92 DONE}
		forge-1.14.4-28.0.92-client.jar Minecraft {minecraft@1.14.4 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['Nigrumrana'/33, l='1.14.4 test', x=68.88, y=73.00, z=858.58]]
	Data Packs: mod:wyrmroost, mod:forge, mod:citadel, vanilla
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by WolfShotz** [comment]
Known. Was hoping this would be a rare case.
Also, future cases, please post the reports in a paste bin 😅
